<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Documents</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
  </head>
  <body>

    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Documents</h4>
          <div class="btn-group pull-right">
            <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('search'); ?>">Search</a>
          </div>
        </div>
      </div>  
      
      <?php if (!isset($_POST['submit'])): ?>
      <div>
        <div class="alert alert-danger">
          This is a public demo application. Documents uploaded are publicly accessible and searchable. Avoid uploading confidential or sensitive information, and use the <a href="<?php echo $data['router']->pathFor('legal'); ?>">Reset System</a> option to delete all data from the application.
        </div>
        <form method="post" enctype="multipart/form-data" action="<?php echo $data['router']->pathFor('add'); ?>">
          <input type="hidden" name="MAX_FILE_SIZE" value="300000000" />
          <div class="form-group">
            <label for="upload">File</label>
            <span class="btn btn-default btn-file">
              <input type="file" name="upload" />
            </span>
          </div>  
          <div class="form-group">
            <label for="body">Description</label>
            <textarea name="description" id="description" class="form-control" rows="3"></textarea>
          </div>
        <div class="form-group">
          <button type="submit" name="submit" class="btn btn-primary">Add</button>
        </div>          
        </form>
      </div>
      <?php else: ?>
      <div>
        <div class="alert alert-success">
          <strong>Success!</strong> Your document <strong><?php echo $data['object']; ?></strong> was added. <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('add'); ?>">Add another?</a>
        </div>
        <div>
         The following keywords were extracted and stored: 
          <ul>
          <?php foreach ($data['keywords'] as $k): ?> 
            <li><?php echo $k; ?></li> 
          <?php endforeach; ?> 
          </ul> 
        </div>
      </div>        
      <p>This operation made use of data generated through <a href="http://www.ibm.com/smarterplanet/us/en/ibmwatson/">IBM Watson</a> and <a href="https://www.alchemyapi.com/">AlchemyAPI</a> services.</p>
      <?php endif; ?>
    </div>
      
    <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn-sm">Legal</a>
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-danger btn-sm">Reset System</a>
    </div> 
    
  </body>
</html>