<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Documents</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
  </head>
  <body>

    <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Documents</h4>
          <div class="btn-group pull-right">
            <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('add'); ?>">Add</a>
          </div>
        </div>
      </div>  
      
      <div class="panel panel-default">
        <form method="get" action="<?php echo $data['router']->pathFor('search'); ?>">
          <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button type="submit" class="btn btn-default">Search</button>
            </span>
          </div>  
        </form>
      </div>  
    
    <?php if (isset($data['results']) && count($data['results'])): ?>
      <h4>Search Results</h4>
      <ul class="list-group row clearfix">
      <?php foreach ($data['results'] as $doc): ?>
        <li class="list-group-item clearfix" style="border:none">
        <strong><?php echo $doc['name']; ?></strong> <a href="<?php echo $data['router']->pathFor('download', array('id' => $doc['name'])); ?>" class="btn-sm btn-success">Download</a> <br /> 
        <?php echo $doc['description']; ?> <br /> 
        Last updated: <?php echo date('d M Y', $doc['updated']); ?> <br /> 
        </li>
      <?php endforeach; ?>
      </ul>
      <p>This operation made use of data generated through <a href="http://www.ibm.com/smarterplanet/us/en/ibmwatson/">IBM Watson</a> and <a href="https://www.alchemyapi.com/">AlchemyAPI</a> services.</p>
    <?php endif; ?>
    </div> 
    
    <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn-sm">Legal</a>
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn-sm">Reset System</a>
      </p>
    </div> 
    
  </body>
</html>